apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  externalIPs:
  - 192.168.122.50
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80
      nodePort: 30000
      name: http
    - protocol: TCP
      port: 8089
      targetPort: 443
      nodePort: 30001
      name: https
