apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  externalIPs:
  - 192.168.122.50
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
