apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  externalIPs:
  - 192.168.122.229
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
