apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  externalIPs:
  - 192.168.122.50
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32100
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32101
      name: https
